### ISSUE TITLE
Error in sl_policy.py Output with NELL-995 Dataset

### ISSUE THREAD

**Issue by YYForReal** [superheavytail/deeppath-pytorch#1]
**Issue Description:**

I am encountering an issue when running the `sl_policy.py` script in the DeepPath framework using the NELL-985 dataset. Many training samples are unable to find a path, as indicated by the output. 

**Steps to Reproduce:**
1. Prepare NELL-985 dataset.
2. Run `sl_policy.py` with the following command: `python sl_policy.py`. （default relation: `concept_agentbelongstoorganization`）
3. Observe the output as mentioned in the provided log.

**Expected Behavior:**

I expected the model would successfully find paths for the training samples in the NELL-985 dataset.

**Actual Behavior:**

The model is unable to find paths for a significant number of training samples.

```
...
Episode 489
Training Sample: concept_person_jim     concept_recordlabel_friends     concept:agentbelongstoorganization
Cannot find a path
Episode 490
Training Sample: concept_televisionstation_kdsd_tv      concept_company_pbs     concept:agentbelongstoorganization
Cannot find a path
Episode 491
Training Sample: concept_televisionstation_wnpb_tv      concept_company_pbs     concept:agentbelongstoorganization
Cannot find a path
Episode 492
Training Sample: concept_televisionstation_wntv concept_company_pbs     concept:agentbelongstoorganization
Cannot find a path
Episode 493
Training Sample: concept_city_bush      concept_politicalparty_house    concept:agentbelongstoorganization
Cannot find a path
Episode 494
Training Sample: concept_musicartist_son        concept_politicalparty_house    concept:agentbelongstoorganization
Cannot find a path
Episode 495
Training Sample: concept_televisionstation_wund_tv      concept_company_pbs     concept:agentbelongstoorganization
Cannot find a path
Episode 496
Training Sample: concept_televisionstation_wnvt concept_company_pbs     concept:agentbelongstoorganization
Cannot find a path
Episode 497
Training Sample: concept_athlete_print  concept_automobilemaker_card    concept:agentbelongstoorganization
Cannot find a path
Episode 498
Training Sample: concept_person_stephen concept_company_apple001        concept:agentbelongstoorganization
Cannot find a path
Episode 499
Training Sample: concept_televisionstation_wfiq concept_company_pbs     concept:agentbelongstoorganization
Cannot find a path
model saved
```

**Comment by superheavytail** [comment]
This is a common issue that occurs in the original code. I experienced the same issue.
(paper: https://arxiv.org/abs/1707.06690, github: https://github.com/xwhan/DeepPath)

My repository primarily focuses on refactoring the code from TensorFlow to PyTorch, and does not include improvements to the algorithm itself.

However, I have another thought. It's possible that the discrepancy arises because the original repository used by the author is NELL-995, while you mentioned using NELL-985. (Though, I don't believe this to be a significant reason.)

Thank you for your interest.

**Comment by YYForReal** [comment]
Thank you for your response. I'll try switching to a different dataset and see if that resolves the issue.
